### ISSUE TITLE
Retaining some future events?

### ISSUE THREAD

**Issue by timmy-mac** [jamesgurung/timetable-calendar-generator#3]
Hi James,

It must be that time of year again!  I've just cobbled together a [script](http://www.edugeek.net/forums/cloud-services/198746-sims-google-calendar.html) that automates the retrieval of the two reports from SIMS and manipulates the output into a usable format for timetable-calendar-generator. Planning to run it nightly or weekly...

Students who change groups and teachers of our 'carousel' subjects should be pleased.  The only person it's going to irritate is actually me! - I 'plan' (loosely) in Google Calendar like so:
![image](https://user-images.githubusercontent.com/34206922/62836371-faf54500-bc59-11e9-939c-d2417722affc.png)

So I will lose my 'planning' each time it runs.

I'm thinking of adapting your work so that it doesn't delete the future event if the title of the event is longer than, say, 10 characters.  I know I'd end up with a duplicate lesson for each one where I'd edited the title but I could live with tidying those up...  I'm not often more that a couple of days in front!

I'm totally unfamiliar with C# but have spotted the following section of code. Am I right in thinking if I can figure out the syntax I could just drop an 'if' statement in to here, testing the length of ev.summary?

> private async Task DeleteEventsAsync(string calendarId, IEnumerable<Event> events)
>     {
>       var deleteBatch = new UnlimitedBatch(Service);
>       foreach (var ev in events)
>       {
>         _if length of ev.summary < 10...._
>         deleteBatch.Queue(Service.Events.Delete(calendarId, ev.Id));
>       }

Presumably I'd need to recompile the app at that point too?

Many thanks,

Tim

**Comment by jamesgurung** [comment]
The `GoogleCalendarEventComparer` is used to determine which events have changed. At the moment, events are considered different if they have different titles - this causes the old ones to be deleted, and new events created in their place. Only events with identical titles are left alone.

To adapt this for your use case, I'd suggest changing [this line](https://github.com/jamesgurung/timetable-calendar-generator/blob/67adff004b8fef5e0371c05fc1eb7b52732e62e8/src/CalendarWriters/Google/GoogleCalendarEventComparer.cs#L20) to:

```c#
GetOriginalTitle(x.Summary) == GetOriginalTitle(y.Summary) &&
```

Then implement the `GetOriginalTitle` function to pick out the portion of the event title that comes before the hyphen:

```c#
private static string GetOriginalTitle(string title) {
  if (title is null) return null;
  var index = title.IndexOf('-');
  if (index < 0) return title;
  return title.Substring(0, index).Trim();
}
```

So now an event is not detected as changed when you add a hyphen followed by the lesson topic. For example, "P4. 10TT/Ph" and "P4. 10TT/Ph - resultant forces" would be considered the same event.

You would also need to change the implementation of `GetHashCode` to replace `ev.Summary` with `GetOriginalTitle(ev.Summary)`, so that it is consistent.

I haven't tested this code, but hope it points you in the right direction. It seems like a useful suggestion, so I may build it in to a future release.

**Comment by timmy-mac** [comment]
Thanks for that James..  will give it a whirl at some point in the next day or so and report back!

Tim

**Comment by jamesgurung** [comment]
It's probably a bit quicker for me to do this, as I have all the tooling set up already.

I've just added a [new release](https://github.com/jamesgurung/timetable-calendar-generator/releases/tag/v3.2.1-tim), please try it and let me know how you get along.

**Comment by timmy-mac** [comment]
![image](https://user-images.githubusercontent.com/34206922/62838082-3fd7a680-bc6f-11e9-96c9-dd6a377f04e6.png)

![image](https://user-images.githubusercontent.com/34206922/62838203-db1d4b80-bc70-11e9-83de-8ee3bd51c66e.png)

Passed the test! 

Greatly appreciated..  it certainly was quicker you doing it :-)

**Comment by jamesgurung** [comment]
Awesome, thanks for testing!
